[package]
name = "xnbparse"
version = "2.0.2"
edition = "2021"
authors = ["Mason Soroka-Gill <Mordinel@pm.me>"]
repository = "https://github.com/Mordinel/xnbparse"
description = "Partial xnb file parser"
license = "Apache-2.0"
publish = false

